version: '3'
services:
  db: 
    image: postgres:12.0
    environment:
      POSTGRES_PASSWORD: dfnheif
    volumes:
      - valera:/var/lib/postgresql/data

  acceptor:
    image: acceptor:test
    environment:
      POSTGRES_PASSWORD: dfnheif
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  valera:
