version: 2.1
jobs:
  build:
    docker:
     - image: circleci/golang:1.13.0
    steps:
      - checkout
      - run:
          name: The first step
          command: |
            echo 'H W !'
            echo 'This is the delivery pipeline'
      - run:
          name: Code has arrived
          command: |
            ls -lha
            echo '^^^That should look familiar^^^'

      - run:
          name: Running in a unique container
          command: go version


