version: 2.1
jobs:
  testing:
    docker:
     - image: circleci/golang:1.13.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod install
      - run:
          name: Go test
          command: go test ...G

      - run:
          name: Running in a unique container
          command: go version
