version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.0

    steps:
      - checkout

      - restore_cache:
          key: go-dependencies-{{ checksum "go.sum" }}

      - run:
          name: Install dependencies
          command: go mod download

      - save_cache:
          key: go-dependencies-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg" 

      - run:
          name: Go test
          command: go test ./...

  build_and_push:
    docker:
      - image: docker:18.06.0-ce

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Setup environment
          command: |
            echo 'export IMAGE_TAG=latest' >> $BASH_ENV
            echo 'export IMAGE_NAME=acceptor' >> $BASH_ENV

      - run:
          name: Build and push Docker image
          command: |
            source $BASH_ENV
            docker build -t pitshifer/$IMAGE_NAME:$IMAGE_TAG .
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker push pitshifer/$IMAGE_NAME:$IMAGE_TAG

  deliver:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over ssh
          command: ssh $SSH_USER@$SSH_HOST "cd ./acceptor &&
            docker pull pitshifer/acceptor &&
            docker-compose down &&
            docker-compose up -d &&
            docker image prune -f"

workflows:
  version: 2
  deploy-dev:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - master

      - deliver:
          filters:
            branches:
              only:
                - master
          requires:
            - build_and_push
